name: Develop-LTB

on:
    push:
        paths:
            - ".github/workflows/*.yml"
            - "src/**"
        branches: ["develop"]
    pull_request:
        paths:
            - ".github/workflows/*.yml"
            - "src/**"
        branches: ["develop"]

jobs:
    DevelopLint:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Lint
              run: echo lint

    DevelopTest:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Test
              run: echo test

    DevelopBuild:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Build
              run: echo build
