name: Main-LTBD

on:
    push:
        paths:
            - ".github/workflows/*.yml"
            - "src/**"
        branches: ["main"]
    pull_request:
        paths:
            - ".github/workflows/*.yml"
            - "src/**"
        branches: ["main"]

jobs:
    MainLintTestBuild:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Lint
              run: npm run all

            - name: Start Test
              run: npm run test-c

            - name: Start Build
              run: npm run build

    FireBase-Pre-Deploy:
        environment: FireBase-Pre-Deploy
        needs: [MainLintTestBuild]
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Build
              run: npm run build

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: dist
                  name: dist-FB-Pre-Deploy

    FireBase-Deploy:
        environment: FireBase-Deploy
        needs: [MainLintTestBuild]
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Build
              run: npm run build

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  path: dist
                  name: dist-FB-Deploy
