name: Release-LTBD 🚀

on:
    push:
        paths:
            - ".github/workflows/*.yml"
            - "src/**"
        branches: ["release/*"]
    pull_request:
        paths:
            - ".github/workflows/*.yml"
            - "src/**"
        branches: ["release/*"]
env:
    API_KEY: ${{ secrets.API_KEY }}
    URL: ${{ secrets.URL }}

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    ReleaseLintTestBuild:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Lint
              run: npm run all

            - name: Start Test
              run: npm run test

            - name: Start Build
              run: npm run build

    FireBase-Pre-Deploy:
        environment: FireBase-Pre-Deploy
        env:
            MODE_ENV_SITE: ${{ vars.MODE_ENV_SITE}}
        needs: [ReleaseLintTestBuild]
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Build
              run: npm run build

            - name: FireBase to Pre-Deploy
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHAVA_TEST_SITE }}
                  projectId: shava-test-site
                  expires: 1d
                  channelId: Pre-Deploy

    FireBase-Deploy:
        environment: FireBase-Deploy
        needs: [ReleaseLintTestBuild]
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: node_modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Package
              run: npm ci

            - name: Start Build
              run: npm run build

            - name: FireBase to Deploy
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHAVA_TEST_SITE }}
                  channelId: live
                  projectId: shava-test-site
