name: Test-Actions2

on:
    push:
        branches: ["main"]

    pull_request:
        branches: ["main"]

jobs:
    EchoTest1:
        if: ${{ github.ref_name == 'main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Echo test 1
              run: echo test 1 - ${{ github.ref_name }}
