name: Test-Actions2

on:
    push:
        branches: ["main"]

    pull_request:
        branches: ["main"]

env:
    ART: ${{ github.event_name }}

jobs:
    EchoTest1:
        runs-on: ubuntu-latest
        steps:
            - name: Echo test 1
              run: echo test ${{ env.ART }}
